version: '3.8'

services:
  bot_service:
    build: .
    container_name: bot_container
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
